openapi: 3.0.0
info:
  title: Lunch API
  version: 0.1.9

paths:
  /: 
    get: 
      description: is working 
      responses:  
        200: 
          description: Success with yes  
  /lunch: 
    get: 
      description: Get all Employee Lunch data
      responses:
        200: 
          description: Success  
    post: 
      summary: Create an new Employee lunch
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeId:
                  type: number
                  required: true
                name:
                  type: string
                  required: true
                lunch:
                  type: boolean
                  required: true       
                date:
                  type: string
      responses:  
        201: 
          description: Created  
  /lunch/{id}:
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeId:
                  type: number
                  required: true
                name:
                  type: string
                  required: true
                lunch:
                  type: boolean
                  required: true       
                date:
                  type: string
      responses:  
        201: 
          description: Created  
    
    